#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

BASE_OUTPUT_DIR="${RUSTRAIN_DISTRIBUTED_BASE_OUTPUT_DIR:-/tmp/rustrain-runs/qwen-session-dp2-sft-max-samples-resume-base-$(date +%Y%m%d-%H%M%S)-$$}"
RESUME_OUTPUT_DIR="${RUSTRAIN_DISTRIBUTED_RESUME_OUTPUT_DIR:-/tmp/rustrain-runs/qwen-session-dp2-sft-max-samples-resume-continue-$(date +%Y%m%d-%H%M%S)-$$}"

RUSTRAIN_DISTRIBUTED_BASE_OUTPUT_DIR="${BASE_OUTPUT_DIR}" \
RUSTRAIN_DISTRIBUTED_RESUME_OUTPUT_DIR="${RESUME_OUTPUT_DIR}" \
RUSTRAIN_QWEN_SESSION_DP_CONFIG="${RUSTRAIN_QWEN_SESSION_DP_CONFIG:-configs/qwen_session_dp2_sft_max_samples.toml}" \
RUSTRAIN_EXPECTED_DATASET_ORDER_SEED="${RUSTRAIN_EXPECTED_DATASET_ORDER_SEED:-777}" \
RUSTRAIN_EXPECTED_DATASET_TOTAL_SAMPLES="${RUSTRAIN_EXPECTED_DATASET_TOTAL_SAMPLES:-4}" \
RUSTRAIN_EXPECTED_DATASET_TRAIN_SAMPLES="${RUSTRAIN_EXPECTED_DATASET_TRAIN_SAMPLES:-3}" \
RUSTRAIN_EXPECTED_DATASET_EVAL_SAMPLES="${RUSTRAIN_EXPECTED_DATASET_EVAL_SAMPLES:-1}" \
RUSTRAIN_EXPECTED_DATASET_SOURCE_FILES="${RUSTRAIN_EXPECTED_DATASET_SOURCE_FILES:-data/sft_toy/instructions.jsonl}" \
RUSTRAIN_EXPECTED_DATASET_SOURCE_SAMPLE_COUNTS="${RUSTRAIN_EXPECTED_DATASET_SOURCE_SAMPLE_COUNTS:-data/sft_toy/instructions.jsonl:4}" \
RUSTRAIN_EXPECTED_DATASET_FINGERPRINT="${RUSTRAIN_EXPECTED_DATASET_FINGERPRINT:-3bfd266239e4b9b9}" \
bash "${SCRIPT_DIR}/verify_qwen_session_dp2_resume_worker.sh"
